apiVersion: apps/v1
kind: Deployment
metadata:
  name: one-piece-whoami
  namespace: auth
  labels:
    project: onepiece-api
    component: test-upstream
spec:
  replicas: 1
  selector:
    matchLabels:
      app: one-piece-whoami
  template:
    metadata:
      labels:
        app: one-piece-whoami
        project: onepiece-api
        component: test-upstream
    spec:
      containers:
        - name: whoami
          image: traefik/whoami:v1.10
          ports:
            - name: http
              containerPort: 80
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi
---
apiVersion: v1
kind: Service
metadata:
  name: one-piece-whoami
  namespace: auth
  labels:
    project: onepiece-api
    component: test-upstream
spec:
  type: ClusterIP
  selector:
    app: one-piece-whoami
  ports:
    - name: http
      port: 80
      targetPort: http
