apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    project: onepiece-api
    component: {{ .Values.component }}
spec:
  parentRefs:
    - name: {{ .Values.gateway.name }}
      namespace: {{ .Values.gateway.namespace }}
  {{- with .Values.hostnames }}
  hostnames:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.paths }}
    - matches:
        - path:
            type: PathPrefix
            value: {{ .path }}
      {{- if .redirect }}
      filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            hostname: {{ .redirect.hostname }}
            {{- with .redirect.path }}
            path:
              type: ReplaceFullPath
              replaceFullPath: {{ . }}
            {{- end }}
            statusCode: {{ .redirect.statusCode }}
      {{- else }}
      backendRefs:
        - name: {{ .backendServiceName }}
          port: {{ .backendServicePort }}
      {{- end }}
    {{- end }}
